[package]
name = "tasha"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.6.0"
clap = { version = "4.5.4", features = ["derive"] }
log = "0.4.21"
serde = { version = "1.0.203", features = ["derive"] }
thiserror = "1.0.61"
tokio = { version = "1.38.0", features = ["full"] }
toml = "0.8.14"
